; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = Transmitter-TX
test_dir = test

; ============================================================================
; Трансмиттер (передатчик)
; ============================================================================
[env:Transmitter-TX]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/cu.usbserial-144301
build_flags =
  -DTRANSMITTER_MODE
lib_deps =
  bblanchon/ArduinoJson@^6.18.3
  links2004/WebSockets@^2.4.1
build_src_filter =
  +<core/transmitter_main.cpp>
  +<drivers/ir_transmitter.cpp>
  +<utils/config.cpp>
  +<drivers/battery/>
  +<drivers/espnow_transmitter.cpp>
  -<.git/>
  -<.svn/>
  -<examples/>
  -<tests/>
  -<core/receiver_main.cpp>
  -<core/measurement_core.cpp>

; ============================================================================
; Ресивер (приемник)
; ============================================================================
[env:Receiver-RX]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-14330
upload_port = /dev/cu.usbserial-14330
build_flags =
  -DRECEIVER_MODE
lib_deps =
  bblanchon/ArduinoJson@^6.18.3
  links2004/WebSockets@^2.4.1
build_src_filter =
  +<core/receiver_main.cpp>
  +<modules/web_handlers.cpp>
  +<modules/web_content.cpp>
  +<modules/measurements_side_effects.cpp>
  +<modules/websocket_handlers.cpp>
  +<utils/config.cpp>
  +<core/measurement_core.cpp>
  +<drivers/battery/>
  +<drivers/espnow_receiver.cpp>
  +<drivers/espnow_broadcast.cpp>
  +<modules/transmitter_data.cpp>
  -<.git/>
  -<.svn/>
  -<examples/>
  -<tests/>
  -<core/tx_main.cpp>
  -<core/transmitter_main.cpp>

; ============================================================================
; Тестовое окружение (Native Testing на хосте)
; ============================================================================
[env:native-tests]
platform = native
test_framework = unity

# Флаги для macOS/Linux
build_flags = 
  -DUNITY_INCLUDE_DOUBLE
  -DUNIT_TEST
  -DARDUINO=1

